package shipping

import (
	"github.com/jackmanlabs/bucket"
)

var states []bucket.HTMLOption = []bucket.HTMLOption{
	{"Alabama", "AL", false},
	{"Alaska", "AK", false},
	{"Arizona", "AZ", false},
	{"Arkansas", "AR", false},
	{"California", "CA", false},
	{"Colorado", "CO", false},
	{"Connecticut", "CT", false},
	{"Delaware", "DE", false},
	{"Florida", "FL", false},
	{"Georgia", "GA", false},
	{"Hawaii", "HI", false},
	{"Idaho", "ID", false},
	{"Illinois", "IL", false},
	{"Indiana", "IN", false},
	{"Iowa", "IA", false},
	{"Kansas", "KS", false},
	{"Kentucky", "KY", false},
	{"Louisiana", "LA", false},
	{"Maine", "ME", false},
	{"Maryland", "MD", false},
	{"Massachusetts", "MA", false},
	{"Michigan", "MI", false},
	{"Minnesota", "MN", false},
	{"Mississippi", "MS", false},
	{"Missouri", "MO", false},
	{"Montana", "MT", false},
	{"Nebraska", "NE", false},
	{"Nevada", "NV", false},
	{"New Hampshire", "NH", false},
	{"New Jersey", "NJ", false},
	{"New Mexico", "NM", false},
	{"New York", "NY", false},
	{"North Carolina", "NC", false},
	{"North Dakota", "ND", false},
	{"Ohio", "OH", false},
	{"Oklahoma", "OK", false},
	{"Oregon", "OR", false},
	{"Pennsylvania", "PA", false},
	{"Rhode Island", "RI", false},
	{"South Carolina", "SC", false},
	{"South Dakota", "SD", false},
	{"Tennessee", "TN", false},
	{"Texas", "TX", false},
	{"Utah", "UT", false},
	{"Vermont", "VT", false},
	{"Virginia", "VA", false},
	{"Washington", "WA", false},
	{"West Virginia", "WV", false},
	{"Wisconsin", "WI", false},
	{"Wyoming", "WY", false}}

var countries []bucket.HTMLOption = []bucket.HTMLOption{
	{"United States of America", "US", false}}

//		{"Afghanistan", "AF", false},
//		{"Åland", "AX", false},
//		{"Albania", "AL", false},
//		{"Algeria", "DZ", false},
//		{"American Samoa", "AS", false},
//		{"Andorra", "AD", false},
//		{"Angola", "AO", false},
//		{"Anguilla", "AI", false},
//		{"Antarctica", "AQ", false},
//		{"Antigua and Barbuda", "AG", false},
//		{"Argentina", "AR", false},
//		{"Armenia", "AM", false},
//		{"Aruba", "AW", false},
//		{"Australia", "AU", false},
//		{"Austria", "AT", false},
//		{"Azerbaijan", "AZ", false},
//		{"Bahamas", "BS", false},
//		{"Bahrain", "BH", false},
//		{"Bangladesh", "BD", false},
//		{"Barbados", "BB", false},
//		{"Belarus", "BY", false},
//		{"Belgium", "BE", false},
//		{"Belize", "BZ", false},
//		{"Benin", "BJ", false},
//		{"Bermuda", "BM", false},
//		{"Bhutan", "BT", false},
//		{"Bolivia", "BO", false},
//		{"Bonaire, Sint Eustatius and Saba", "BQ", false},
//		{"Bosnia and Herzegovina", "BA", false},
//		{"Botswana", "BW", false},
//		{"Bouvet Island", "BV", false},
//		{"Brazil", "BR", false},
//		{"British Indian Ocean Territory", "IO", false},
//		{"Brunei Darussalam", "BN", false},
//		{"Bulgaria", "BG", false},
//		{"Burkina Faso", "BF", false},
//		{"Burundi", "BI", false},
//		{"Cambodia", "KH", false},
//		{"Cameroon", "CM", false},
//		{"Cape Verde", "CV", false},
//		{"Canada", "CA", false},
//		{"Cayman Islands", "KY", false},
//		{"Central African Republic", "CF", false},
//		{"Chad", "TD", false},
//		{"Chile", "CL", false},
//		{"China", "CN", false},
//		{"Christmas Island", "CX", false},
//		{"Cocos (Keeling) Islands", "CC", false},
//		{"Colombia", "CO", false},
//		{"Comoros", "KM", false},
//		{"Congo (Brazzaville)", "CG", false},
//		{"Congo (Kinshasa)", "CD", false},
//		{"Cook Islands", "CK", false},
//		{"Costa Rica", "CR", false},
//		{"Côte d'Ivoire", "CI", false},
//		{"Croatia", "HR", false},
//		{"Cuba", "CU", false},
//		{"Curaçao", "CW", false},
//		{"Cyprus", "CY", false},
//		{"Czech Republic", "CZ", false},
//		{"Denmark", "DK", false},
//		{"Djibouti", "DJ", false},
//		{"Dominica", "DM", false},
//		{"Dominican Republic", "DO", false},
//		{"Ecuador", "EC", false},
//		{"Egypt", "EG", false},
//		{"El Salvador", "SV", false},
//		{"Equatorial Guinea", "GQ", false},
//		{"Eritrea", "ER", false},
//		{"Estonia", "EE", false},
//		{"Ethiopia", "ET", false},
//		{"Falkland Islands", "FK", false},
//		{"Faroe Islands", "FO", false},
//		{"Fiji", "FJ", false},
//		{"Finland", "FI", false},
//		{"France", "FR", false},
//		{"French Guiana", "GF", false},
//		{"French Polynesia", "PF", false},
//		{"French Southern Lands", "TF", false},
//		{"Gabon", "GA", false},
//		{"Gambia", "GM", false},
//		{"Georgia", "GE", false},
//		{"Germany", "DE", false},
//		{"Ghana", "GH", false},
//		{"Gibraltar", "GI", false},
//		{"Greece", "GR", false},
//		{"Greenland", "GL", false},
//		{"Grenada", "GD", false},
//		{"Guadeloupe", "GP", false},
//		{"Guam", "GU", false},
//		{"Guatemala", "GT", false},
//		{"Guernsey", "GG", false},
//		{"Guinea", "GN", false},
//		{"Guinea-Bissau", "GW", false},
//		{"Guyana", "GY", false},
//		{"Haiti", "HT", false},
//		{"Heard and McDonald Islands", "HM", false},
//		{"Honduras", "HN", false},
//		{"Hong Kong", "HK", false},
//		{"Hungary", "HU", false},
//		{"Iceland", "IS", false},
//		{"India", "IN", false},
//		{"Indonesia", "ID", false},
//		{"Iran", "IR", false},
//		{"Iraq", "IQ", false},
//		{"Ireland", "IE", false},
//		{"Isle of Man", "IM", false},
//		{"Israel", "IL", false},
//		{"Italy", "IT", false},
//		{"Jamaica", "JM", false},
//		{"Japan", "JP", false},
//		{"Jersey", "JE", false},
//		{"Jordan", "JO", false},
//		{"Kazakhstan", "KZ", false},
//		{"Kenya", "KE", false},
//		{"Kiribati", "KI", false},
//		{"Korea, North", "KP", false},
//		{"Korea, South", "KR", false},
//		{"Kuwait", "KW", false},
//		{"Kyrgyzstan", "KG", false},
//		{"Laos", "LA", false},
//		{"Latvia", "LV", false},
//		{"Lebanon", "LB", false},
//		{"Lesotho", "LS", false},
//		{"Liberia", "LR", false},
//		{"Libya", "LY", false},
//		{"Liechtenstein", "LI", false},
//		{"Lithuania", "LT", false},
//		{"Luxembourg", "LU", false},
//		{"Macau", "MO", false},
//		{"Macedonia", "MK", false},
//		{"Madagascar", "MG", false},
//		{"Malawi", "MW", false},
//		{"Malaysia", "MY", false},
//		{"Maldives", "MV", false},
//		{"Mali", "ML", false},
//		{"Malta", "MT", false},
//		{"Marshall Islands", "MH", false},
//		{"Martinique", "MQ", false},
//		{"Mauritania", "MR", false},
//		{"Mauritius", "MU", false},
//		{"Mayotte", "YT", false},
//		{"Mexico", "MX", false},
//		{"Micronesia", "FM", false},
//		{"Moldova", "MD", false},
//		{"Monaco", "MC", false},
//		{"Mongolia", "MN", false},
//		{"Montenegro", "ME", false},
//		{"Montserrat", "MS", false},
//		{"Morocco", "MA", false},
//		{"Mozambique", "MZ", false},
//		{"Myanmar", "MM", false},
//		{"Namibia", "NA", false},
//		{"Nauru", "NR", false},
//		{"Nepal", "NP", false},
//		{"Netherlands", "NL", false},
//		{"New Caledonia", "NC", false},
//		{"New Zealand", "NZ", false},
//		{"Nicaragua", "NI", false},
//		{"Niger", "NE", false},
//		{"Nigeria", "NG", false},
//		{"Niue", "NU", false},
//		{"Norfolk Island", "NF", false},
//		{"Northern Mariana Islands", "MP", false},
//		{"Norway", "NO", false},
//		{"Oman", "OM", false},
//		{"Pakistan", "PK", false},
//		{"Palau", "PW", false},
//		{"Palestine", "PS", false},
//		{"Panama", "PA", false},
//		{"Papua New Guinea", "PG", false},
//		{"Paraguay", "PY", false},
//		{"Peru", "PE", false},
//		{"Philippines", "PH", false},
//		{"Pitcairn", "PN", false},
//		{"Poland", "PL", false},
//		{"Portugal", "PT", false},
//		{"Puerto Rico", "PR", false},
//		{"Qatar", "QA", false},
//		{"Reunion", "RE", false},
//		{"Romania", "RO", false},
//		{"Russian Federation", "RU", false},
//		{"Rwanda", "RW", false},
//		{"Saint Barthélemy", "BL", false},
//		{"Saint Helena", "SH", false},
//		{"Saint Kitts and Nevis", "KN", false},
//		{"Saint Lucia", "LC", false},
//		{"Saint Martin (French part)", "MF", false},
//		{"Saint Pierre and Miquelon", "PM", false},
//		{"Saint Vincent and the Grenadines", "VC", false},
//		{"Samoa", "WS", false},
//		{"San Marino", "SM", false},
//		{"Sao Tome and Principe", "ST", false},
//		{"Saudi Arabia", "SA", false},
//		{"Senegal", "SN", false},
//		{"Serbia", "RS", false},
//		{"Seychelles", "SC", false},
//		{"Sierra Leone", "SL", false},
//		{"Singapore", "SG", false},
//		{"Sint Maarten", "SX", false},
//		{"Slovakia", "SK", false},
//		{"Slovenia", "SI", false},
//		{"Solomon Islands", "SB", false},
//		{"Somalia", "SO", false},
//		{"South Africa", "ZA", false},
//		{"South Georgia and South Sandwich Islands", "GS", false},
//		{"South Sudan", "SS", false},
//		{"Spain", "ES", false},
//		{"Sri Lanka", "LK", false},
//		{"Sudan", "SD", false},
//		{"Suriname", "SR", false},
//		{"Svalbard and Jan Mayen Islands", "SJ", false},
//		{"Swaziland", "SZ", false},
//		{"Sweden", "SE", false},
//		{"Switzerland", "CH", false},
//		{"Syria", "SY", false},
//		{"Taiwan", "TW", false},
//		{"Tajikistan", "TJ", false},
//		{"Tanzania", "TZ", false},
//		{"Thailand", "TH", false},
//		{"Timor-Leste", "TL", false},
//		{"Togo", "TG", false},
//		{"Tokelau", "TK", false},
//		{"Tonga", "TO", false},
//		{"Trinidad and Tobago", "TT", false},
//		{"Tunisia", "TN", false},
//		{"Turkey", "TR", false},
//		{"Turkmenistan", "TM", false},
//		{"Turks and Caicos Islands", "TC", false},
//		{"Tuvalu", "TV", false},
//		{"Uganda", "UG", false},
//		{"Ukraine", "UA", false},
//		{"United Arab Emirates", "AE", false},
//		{"United Kingdom", "GB", false},
//		{"United States Minor Outlying Islands", "UM", false},
//		{"Uruguay", "UY", false},
//		{"Uzbekistan", "UZ", false},
//		{"Vanuatu", "VU", false},
//		{"Vatican City", "VA", false},
//		{"Venezuela", "VE", false},
//		{"Vietnam", "VN", false},
//		{"Virgin Islands, British", "VG", false},
//		{"Virgin Islands, U.S.", "VI", false},
//		{"Wallis and Futuna Islands", "WF", false},
//		{"Western Sahara", "EH", false},
//		{"Yemen", "YE", false},
//		{"Zambia", "ZM", false},
//		{"Zimbabwe", "ZW", false}
